services:
  - type: web
    name: indoor-plant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn indoor_plant.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: indoor_plant_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com 