services:
  - type: web
    name: indoor-plant
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn indoor_plant.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: indoor_plant_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FEDEX_API_KEY
        sync: false
      - key: FEDEX_API_SECRET
        sync: false

databases:
  - name: indoor_plant_db
    databaseName: indoor_plant
    user: indoor_plant_user
