# Generated by Django 5.1.2 on 2025-07-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_address_customuser_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
    ]
