# Generated by Django 5.1.2 on 2025-07-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bulkpricebracket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkPriceBracket',
        ),
    ]
