# Generated by Django 5.1.2 on 2025-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_delete_bulkpricebracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="care_tip",
            field=models.TextField(blank=True, null=True),
        ),
    ]
