# Generated by Django 5.1.2 on 2025-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_cost_price_alter_product_status_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, help_text="SEO meta title", max_length=255, null=True
            ),
        ),
    ]
