# Generated by Django 5.1.2 on 2025-07-15 20:12

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
