# Generated by Django 5.1.2 on 2025-07-15 23:53

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_quill.fields.QuillField(),
        ),
    ]
